name: Docker

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Extract NSD version from Dockerfile
      run: |
        NSD_VERSION=$(grep "ARG NSD_VERSION" Dockerfile | cut -d= -f 2)
        echo "NSD VERSION: $NSD_VERSION"
        [ -z "$NSD_VERSION" ] && echo "Empty version string" && exit 1
        echo "NSD_VERSION=$NSD_VERSION" >> $GITHUB_ENV

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: |
          ghcr.io/philippkuntschik/nsd:v${{ env.NSD_VERSION }}
          ghcr.io/philippkuntschik/nsd:latest
